sion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import sionLogin.urls as sionLogin
import sionProfile.urls as sionProfile

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/sionLogin/', permanent=True), name='root'),
    url(r'^sionLogin/',include(sionLogin,namespace='sionLogin')),
    url(r'^sionProfile/',include(sionProfile,namespace='sionProfile')),
]

sionLogin/urls.py
from django.conf.urls import url
from .views import index
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^custom_auth/login/$',auth_login,name='auth_login'),
    url(r'^custom_auth/logout/$',auth_logout,name='auth_logout'),
]

sionProfile/urls.py
from django.conf.urls import url
from .views import index, profile

urlpatterns = [
    url(r'^$',index,name='index'),
    url(r'^sionProfile/$',profile,name='sionProfile'),
    ]

sionLogin/models.py
from django.db import models

# Create your models here.

sionProfile/models.py
from django.db import models

# Create your models here.

sionLogin/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .db_helper import DatabaseConnection

# Create your views here.
response = {}

def index(request):
    if 'email_login' in request.session :
        print('logged in')
        response['login'] = True
        return HttpResponseRedirect(reverse('sionProfile:index'))

    else :
        print('not logged in')
        response['login'] = False
        html = 'home.html'
        return render(request, html, response)


def profile(request):
    if 'email_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('fitur1:index'))


    conn = DatabaseConnection()
    conn.cursor.execute("select * from sion.user where email='"+request.session['email_login']+"';")
    row = conn.cursor.fetchone()
    response['email'] = row[0]
    response['nama'] = row[2]
    list_alamat = [x.strip() for x in row[3].split(',')]
    response['alamat'] = list_alamat[0]
    try:
        response['kecamatan'] = list_alamat[1]
        response['kabupaten'] = list_alamat[2]
        response['kode_pos'] = list_alamat[3]
    except:
        #do nothing
        response['kecamatan'] = "-"
        response['kabupaten'] = "-"
        response['kode_pos'] = "-"
        
    response['role'] = request.session['role'].capitalize()
    
    if request.session['role'] == 'donatur' or request.session['role'] == 'relawan' :
        html = 'login_sion/session/profil_donatur_relawan.html'

    elif request.session['role'] == 'sponsor' :
        html = 'login_sion/session/profil_sponsor.html'

    elif request.session['role'] == 'pengurus_organisasi' :
        html = 'login_sion/session/profil_pengurus_organisasi.html'

    return render(request, html, response)

sionProfile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from sionLogin.db_helper import DatabaseConnection

def index(request):
	if 'email_login' in request.session:
		return HttpResponseRedirect(reverse('sionProfile:profile'))

	else:
		return HttpResponseRedirect(reverse('sionLogin:index'))

def profile(request):
	if 'email_login' not in request.session.keys():
		return HttpResponseRedirect(reverse('sionLogin:index'))

	conn = DatabaseConnection()
    conn.cursor.execute("select email, nama, alamat from sion.user where email='"+request.session['email_login']+"';")
    row = conn.cursor.fetchone()
    response['email'] = row[0]
    response['nama'] = row[1]
    response['alamat'] = row[2]

    if request.session['role'] == 'donatur':
    	conn.cursor.execute("select saldo from sion.donatur where email='"+request.session['email_login']+"';")
    	row = conn.cursor.fetchone()
    	response['saldo'] = row[0]
        html = 'profilDonatur.html'

    elif request.session['role'] == 'relawan' :
    	conn.cursor.execute("select no_hp, tanggal_lahir from sion.relawan where email='"+request.session['email_login']+"';")
    	row = conn.cursor.fetchone()
    	response['no_hp'] = row[0]
    	response['tanggal_lahir'] = row[1]
        html = 'profilRelawan.html'

    elif request.session['role'] == 'sponsor' :
    	conn.cursor.execute("select logo_sponsor from sion.sponsor where email='"+request.session['email_login']+"';")
    	row = conn.cursor.fetchone()
    	response['logo_sponsor'] = row[0]
        html = 'profilSponsor.html'

    elif request.session['role'] == 'pengurus_organisasi' :
    	conn.cursor.execute("select organisasi from sion.pengurus_organisasi where email='"+request.session['email_login']+"';")
    	row = conn.cursor.fetchone()
    	response['organisasi'] = row[0]
        html = 'profilPengurus.html'

    return render(request, html, response)

sionLogin/templates/header.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css'%}">

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-cloud"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Profil</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Organisasi</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kegiatan&nbsp;</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Buat</a>
              <a class="dropdown-item" href="#">Lihat</a>
            </div>
          </li>
        </ul>
        <a class="btn navbar-btn ml-2 text-white btn-danger">
          <i class="-"></i> Log Out</a>
      </div>
    </div>
  </nav>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>

sionLogin/templates/home.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- PAGE settings -->
  <link rel="icon" href="https://templates.pingendo.com/assets/Pingendo_favicon.ico">
  <title>Styleguide</title>
  <meta name="author" content="Pingendo">
  <!-- CSS dependencies -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>
  <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css'%}">

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-cloud"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#"> About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Contacts</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5 text-center cover" style="background-image: url('../../../Pictures/50a5c71d373c183fb1094d0b2ebfc427.jpg');background-size:cover;">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-3 mb-4 text-center text-primary">
            <b>Organization campaigns are easier with SION</b>
          </h1>
          <p class="lead mb-5">
            <b>Join, donate, and volunteer</b>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2>About</h2>
          <hr>
          <h1 class="display-4"> SION</h1>
          <h1>Sistem Informasi Organisasi Nirlaba</h1>
          <p class="lead">Lead paragraph </p>
          <p>Paragraph. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            <br>
            <i>Italic. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</i>
            <br>
            <b>Bold. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</b>
          </p>
          <div class="blockquote">
            <p class="mb-0">Blockquoute</p>
            <div class="blockquote-footer">Someone famous in
              <cite>My memories</cite>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2>Contact Us</h2>
          <hr> </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a href="#home" class="nav-link active" aria-controls="home" aria-selected="true" data-toggle="tab" id="home-tab" role="tab">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#profile" aria-controls="profile" aria-selected="false" data-toggle="tab" id="profile-tab" role="tab">Profile</a>
            </li>
            <li class="nav-item">
              <a href="#contact" class="nav-link" aria-controls="contact" aria-selected="false" data-toggle="tab" id="contact-tab" role="tab">Contact
                <span class="badge badge-pill badge-warning">!</span>
              </a>
            </li>
          </ul>
          <div class="tab-content my-2" id="myTabContent">
            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</div>
            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</div>
            <div class="tab-pane fade" id="contact" role="tabpanel"
              aria-labelledby="contact-tab">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Consectetur adipiscing elit, sed do eiusmod tempor incididunt. </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 text-center bg-gradient" style="">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">Log In</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 bg-primary text-white bg-gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>User Log in</h1>
          <form action="{% url 'sionLogin:auth_login' %}" method="POST">
            <div class="form-group">
              <label for="InputName">Username</label>
              <input type="text" name="username" class="form-control" id="InputName" placeholder="Your username"> </div>
            <div class="form-group">
              <label for="InputEmail1">Password</label>
              <input type="email" name="password" class="form-control" id="InputEmail1" placeholder="Enter password"> </div>
            <button type="submit" class="btn btn-secondary">Log in</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="py-5 text-center filter-light" style="background-image: url('../../../Pictures/03d4bc2280263c6d64494b927a7cd044.jpg'); background-position: center center; background-size: cover;">
    <div class="container py-5">
      <div class="row">
        <div class="col-md-12">
          <h1 class="display-1">Sign Up</h1>
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                <b>Sponsor</b>
              </h5>
              <p class="card-text">Spare your $</p>
              <a href="#" class="btn btn-primary">Sign Up</a>
            </div>
            <div class="card-body">
              <h5 class="card-title">Donor</h5>
              <p class="card-text">Spare your $</p>
              <a href="#" class="btn btn-primary">Sign Up</a>
            </div>
            <div class="card-body">
              <h5 class="card-title">Volunteer</h5>
              <p class="card-text">Spare your energy</p>
              <a href="#" class="btn btn-primary">Sign Up</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar3SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-center" id="navbar3SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <b>©SION made by kelompok 10 Basdat C</b>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <script src="http://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

sionLogin/templates/regis.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-cloud"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#"> About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Contacts</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5 text-white opaque-overlay filter-light" style="background-image: url(&quot;C:/Users/ATHIFA MICHEL/Pictures/03d4bc2280263c6d64494b927a7cd044.jpg&quot;); background-size: cover;">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-gray-dark text-dark">
            <b>Sponsor Sign Up</b>
          </h1>
          <form class="" method="post" action="https://formspree.io/">
            <div class="form-group">
              <label class="text-dark">Name</label>
              <input type="" name="email" class="form-control" placeholder="name"> </div>
            <div class="form-group">
              <label class="text-dark">Email</label>
              <input type="email" name="password" class="form-control" placeholder="email"> </div>
            <div class="form-group">
              <label class="text-dark">Address</label>
              <input type="" name="password" class="form-control" placeholder="address"> </div>
            <div class="form-group">
              <label class="text-dark">Logo</label>
              <input type="file" name="password" class="form-control-file text-dark" placeholder="Password"> </div>
            <div class="form-group">
              <label class="text-dark">Password</label>
              <input type="password" name="password" class="form-control" placeholder="password"> </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>

sionLogin/templates/regisdonor.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="https://v40.pingendo.com/assets/4.0.0/default/theme.css" type="text/css"> </head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-cloud"></i>
        <b>SION</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#"> About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"> Contacts</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="py-5 text-white opaque-overlay filter-light" style="background-image: url(&quot;C:/Users/ATHIFA MICHEL/Pictures/03d4bc2280263c6d64494b927a7cd044.jpg&quot;); background-size: cover;">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 class="text-gray-dark text-dark">
            <b>Donor Sign Up</b>
          </h1>
          <form class="" method="post" action="https://formspree.io/">
            <div class="form-group">
              <label class="text-dark">Name</label>
              <input type="" name="email" class="form-control" placeholder="name"> </div>
            <div class="form-group">
              <label class="text-dark">Email</label>
              <input type="email" name="password" class="form-control" placeholder="email"> </div>
            <div class="form-group">
              <label class="text-dark">Address</label>
              <input type="" name="password" class="form-control" placeholder="address"> </div>
            <div class="form-group">
              <label class="text-dark">Saldo</label>
              <input type="" name="saldo" class="form-control" placeholder="saldo"> </div>
            <div class="form-group">
              <label for="exampleInputEmail1" class="text-dark">Password</label>
              <input type="" name="password" class="form-control" placeholder="password">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <pingendo onclick="window.open('https://pingendo.com/', '_blank')" style="cursor:pointer;position: fixed;bottom: 10px;right:10px;padding:4px;background-color: #00b0eb;border-radius: 8px; width:250px;display:flex;flex-direction:row;align-items:center;justify-content:center;font-size:14px;color:white">Made with Pingendo Free&nbsp;&nbsp;
    <img src="https://pingendo.com/site-assets/Pingendo_logo_big.png" class="d-block" alt="Pingendo logo" height="16">
  </pingendo>
</body>

</html>